import { describe, expect, it } from 'vitest';
import { existsSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import {
  captureJsonAssetHttpRuntimeUrls,
  captureRepresentativeHttpRuntimeUrls,
  getMissingPackAndRedirectDiagnostics,
} from '@shared/http-url-capture';
import { getFixturePaths } from '@shared/fixture-paths';
import { buildEditorLibraryResourcesBundle } from '@shared/editor-library-bundle';

interface CachedBundleConfig {
  name?: string;
  packs?: Record<string, unknown[]>;
  redirect?: unknown[];
}

interface CachedBundleConfigDiagnostics {
  gameCachesRootExists: boolean;
  configSummaries: Array<{
    name: string;
    packCount: number;
    redirectCount: number;
  }>;
}

async function readSmallProjectCachedBundleConfigs(projectRoot: string): Promise<CachedBundleConfig[]> {
  const gameCachesRoot = join(projectRoot, 'temp', 'writablePath', 'gamecaches');
  if (!existsSync(gameCachesRoot)) {
    return [];
  }

  const configs: CachedBundleConfig[] = [];
  const bundleDirs = await readdir(gameCachesRoot, { withFileTypes: true });
  for (const bundleDir of bundleDirs) {
    if (!bundleDir.isDirectory()) {
      continue;
    }
    const bundleCacheRoot = join(gameCachesRoot, bundleDir.name);
    const files = await readdir(bundleCacheRoot, { withFileTypes: true });
    for (const file of files) {
      if (!file.isFile() || !file.name.endsWith('.json')) {
        continue;
      }
      let config: CachedBundleConfig;
      try {
        config = JSON.parse(await readFile(join(bundleCacheRoot, file.name), 'utf8')) as CachedBundleConfig;
      } catch {
        continue;
      }
      if (config.name && config.packs && config.redirect) {
        configs.push(config);
      }
    }
  }
  return configs;
}

async function inspectSmallProjectCachedBundleConfigDiagnostics(projectRoot: string): Promise<CachedBundleConfigDiagnostics> {
  const gameCachesRoot = join(projectRoot, 'temp', 'writablePath', 'gamecaches');
  const configs = await readSmallProjectCachedBundleConfigs(projectRoot);
  return {
    gameCachesRootExists: existsSync(gameCachesRoot),
    configSummaries: configs.map((config) => ({
      name: config.name!,
      packCount: Object.keys(config.packs ?? {}).length,
      redirectCount: config.redirect?.length ?? 0,
    })),
  };
}

describe('HTTP-base engine URL capture probe', () => {
  it('captures JsonAsset import URL generated by real engine resources.load', async () => {
    const capturedRuntimeUrls = await captureJsonAssetHttpRuntimeUrls();

    expect(capturedRuntimeUrls).toContainEqual({
      url: '/query-extname/e62d10c9-29b9-4d53-833b-5769b524b759',
      routeCategory: 'query-extname',
      sourceOperation: 'resources.load(JsonAsset)',
      expectedArtifactKind: 'extension-replacement',
      probe: 'http-base',
    });
    expect(capturedRuntimeUrls).toContainEqual({
      url: '/assets/resources/import/e6/e62d10c9-29b9-4d53-833b-5769b524b759.json',
      routeCategory: 'import',
      sourceOperation: 'resources.load(JsonAsset)',
      expectedArtifactKind: 'serialized-json',
      probe: 'http-base',
    });
  }, 120_000);

  it('captures ImageAsset native URL generated by real engine resources.load', async () => {
    const capturedRuntimeUrls = await captureRepresentativeHttpRuntimeUrls();
    const nativeImageRequest = capturedRuntimeUrls.find((entry) => entry.routeCategory === 'native');

    expect(nativeImageRequest).toMatchObject({
      routeCategory: 'native',
      sourceOperation: 'resources.load(ImageAsset)',
      expectedArtifactKind: 'native-image',
      probe: 'http-base',
    });
    expect(nativeImageRequest?.url).toMatch(/^\/assets\/resources\/native\/[0-9a-f]{2}\/[0-9a-f-]{36}\.(?:png|jpg|jpeg)$/);
  }, 120_000);

  it('documents current pack and redirect capture gaps without substituting guessed URLs', async () => {
    const paths = getFixturePaths();
    const { config } = await buildEditorLibraryResourcesBundle(paths.editorLibraryRef, { buildFileIndex: false });

    const diagnostics = getMissingPackAndRedirectDiagnostics(config);

    expect(Object.keys(config.packs)).toHaveLength(0);
    expect(config.redirect).toEqual([]);
    expect(diagnostics).toEqual([
      {
        routeCategory: 'pack',
        sourceOperation: 'resources.load(representative frozen resources samples)',
        captured: false,
        missingReason: 'current synthesized resources bundle config has no config.packs entries',
        nextTriggerCondition: 'add or find a frozen sample whose engine config.packs produces a packManager.load URL',
      },
      {
        routeCategory: 'redirect',
        sourceOperation: 'resources.load(representative frozen resources samples)',
        captured: false,
        missingReason: 'current synthesized resources bundle config has no redirect entries',
        nextTriggerCondition: 'add or find a frozen sample whose asset info redirects to another bundle config',
      },
    ]);
  });

  it('documents that representative HTTP-base resource capture does not trigger the small-project extension asset-db domain', async () => {
    const capturedRuntimeUrls = await captureRepresentativeHttpRuntimeUrls();

    expect(capturedRuntimeUrls.length).toBeGreaterThan(0);
    expect(capturedRuntimeUrls.some((entry) => entry.url.includes('view-state-group'))).toBe(false);
    expect(capturedRuntimeUrls.some((entry) => entry.url.includes('cli-extensions'))).toBe(false);
  }, 120_000);

  it('records non-authoritative small-project cached bundle config diagnostics when present', async () => {
    const paths = getFixturePaths();
    const diagnostics = await inspectSmallProjectCachedBundleConfigDiagnostics(paths.projectRoot);

    expect(typeof diagnostics.gameCachesRootExists).toBe('boolean');
    expect(Array.isArray(diagnostics.configSummaries)).toBe(true);
    if (diagnostics.configSummaries.length > 0) {
      expect(
        diagnostics.configSummaries.filter((config) => config.packCount > 0 || config.redirectCount > 0),
        'cached configs are diagnostic only; any non-empty entry must be promoted to a fact-backed pack/redirect capture task',
      ).toEqual([]);
    }
  });
});
