import { describe, expect, it } from 'vitest';
import {
  captureJsonAssetHttpRuntimeUrls,
  captureRepresentativeHttpRuntimeUrls,
  getMissingPackAndRedirectDiagnostics,
} from '@shared/http-url-capture';
import { getFixturePaths } from '@shared/fixture-paths';
import { buildEditorLibraryResourcesBundle } from '@shared/editor-library-bundle';

describe('HTTP-base engine URL capture probe', () => {
  it('captures JsonAsset import URL generated by real engine resources.load', async () => {
    const capturedRuntimeUrls = await captureJsonAssetHttpRuntimeUrls();

    expect(capturedRuntimeUrls).toContainEqual({
      url: '/query-extname/e62d10c9-29b9-4d53-833b-5769b524b759',
      routeCategory: 'query-extname',
      sourceOperation: 'resources.load(JsonAsset)',
      expectedArtifactKind: 'extension-replacement',
      probe: 'http-base',
    });
    expect(capturedRuntimeUrls).toContainEqual({
      url: '/assets/resources/import/e6/e62d10c9-29b9-4d53-833b-5769b524b759.json',
      routeCategory: 'import',
      sourceOperation: 'resources.load(JsonAsset)',
      expectedArtifactKind: 'serialized-json',
      probe: 'http-base',
    });
  });

  it('captures ImageAsset native URL generated by real engine resources.load', async () => {
    const capturedRuntimeUrls = await captureRepresentativeHttpRuntimeUrls();
    const nativeImageRequest = capturedRuntimeUrls.find((entry) => entry.routeCategory === 'native');

    expect(nativeImageRequest).toMatchObject({
      routeCategory: 'native',
      sourceOperation: 'resources.load(ImageAsset)',
      expectedArtifactKind: 'native-image',
      probe: 'http-base',
    });
    expect(nativeImageRequest?.url).toMatch(/^\/assets\/resources\/native\/[0-9a-f]{2}\/[0-9a-f-]{36}\.(?:png|jpg|jpeg)$/);
  });

  it('documents current pack and redirect capture gaps without substituting guessed URLs', async () => {
    const paths = getFixturePaths();
    const { config } = await buildEditorLibraryResourcesBundle(paths.editorLibraryRef, { buildFileIndex: false });

    const diagnostics = getMissingPackAndRedirectDiagnostics(config);

    expect(Object.keys(config.packs)).toHaveLength(0);
    expect(config.redirect).toEqual([]);
    expect(diagnostics).toEqual([
      {
        routeCategory: 'pack',
        sourceOperation: 'resources.load(representative frozen resources samples)',
        captured: false,
        missingReason: 'current synthesized resources bundle config has no config.packs entries',
        nextTriggerCondition: 'add or find a frozen sample whose engine config.packs produces a packManager.load URL',
      },
      {
        routeCategory: 'redirect',
        sourceOperation: 'resources.load(representative frozen resources samples)',
        captured: false,
        missingReason: 'current synthesized resources bundle config has no redirect entries',
        nextTriggerCondition: 'add or find a frozen sample whose asset info redirects to another bundle config',
      },
    ]);
  });
});
