import { describe, expect, it } from 'vitest';
import { captureJsonAssetHttpRuntimeUrls } from '@shared/http-url-capture';

describe('HTTP-base engine URL capture probe', () => {
  it('captures JsonAsset import URL generated by real engine resources.load', async () => {
    const capturedRuntimeUrls = await captureJsonAssetHttpRuntimeUrls();

    expect(capturedRuntimeUrls).toContainEqual({
      url: '/query-extname/e62d10c9-29b9-4d53-833b-5769b524b759',
      routeCategory: 'query-extname',
      sourceOperation: 'resources.load(JsonAsset)',
      expectedArtifactKind: 'extension-replacement',
      probe: 'http-base',
    });
    expect(capturedRuntimeUrls).toContainEqual({
      url: '/assets/resources/import/e6/e62d10c9-29b9-4d53-833b-5769b524b759.json',
      routeCategory: 'import',
      sourceOperation: 'resources.load(JsonAsset)',
      expectedArtifactKind: 'serialized-json',
      probe: 'http-base',
    });
  });
});
